4.4
Jonathan523/SHU-CS-DS-2024W pull request #19
Opened 2024-11-28 12:30 UTC by lyyyyrrrrr

2024-11-28 15:28 UTC, Jonathan523 commented
记得写一下 in 文件

2024-12-01 16:07 UTC, Jonathan523 requested changes

2024-12-01 16:07 UTC, Jonathan523 commented on chapter4/4/src/main.cpp
> +    std::cout << "Please enter the maximum size of the stack: ";
如果这里输入的是`-1`则会直接溢出报错

2024-12-01 16:07 UTC, Jonathan523 commented on chapter4/4/src/main.cpp
> +        std::cout << "How much? ";
这里也是

2024-12-01 16:07 UTC, Jonathan523 commented on chapter4/4/src/main.cpp
> +        std::cout << "How much? ";
这里也是

2024-12-02 02:59 UTC, Jonathan523 approved these changes

2024-12-02 02:59 UTC, ZHANGss-ss approved these changes

2024-12-02 02:59 UTC, ZHANGss-ss commented on chapter4/4/src/main.cpp
> +    std::cout << "Please enter the maximum size of the stack: ";
👀👀

2024-12-02 03:01 UTC, blueshootingstar approved these changes

2024-12-02 03:06 UTC, merged