fix:add in
Jonathan523/SHU-CS-DS-2024W pull request #21
Opened 2024-11-28 15:45 UTC by blueshootingstar

2024-12-01 12:20 UTC, ZHANGss-ss approved these changes

2024-12-01 15:44 UTC, Jonathan523 requested changes

2024-12-01 15:44 UTC, Jonathan523 commented on chapter4/5/include/Stack.hpp
> +    Stack(const int& size = 20);
`Stack` 类中缺少析构，可能造成内存泄漏

2024-12-01 15:44 UTC, Jonathan523 commented on chapter4/5/include/Queue.hpp
> +    Queue(const int& size = 20);
缺少析构，可能造成内存泄漏

2024-12-02 01:49 UTC, lyyyyrrrrr approved these changes

2024-12-02 02:00 UTC, ZHANGss-ss approved these changes

2024-12-02 02:22 UTC, Jonathan523 approved these changes

2024-12-02 02:23 UTC, merged