fix: details of the head of the LinkList.
Jonathan523/SHU-CS-DS-2024W pull request #5
Opened 2024-11-22 03:05 UTC by ZHANGss-ss

This commit fixed errors in Insert and Delete.

2024-11-22 03:25 UTC, Jonathan523 requested changes
38-40 行冗余

2024-11-22 03:37 UTC, ZHANGss-2005 commented
> 38-40 行 temp 冗余

？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

2024-11-22 04:20 UTC, Jonathan523 commented
我的意思是 可以不用 temp 实现相同功能
p->next=q->next
q->next=p
你还是把他放 else 里面吧

2024-11-22 04:20 UTC, Jonathan523 requested changes
去改吧

2024-11-22 04:37 UTC, ZHANGss-2005 commented
> 我的意思是 可以不用 temp 实现相同功能 p->next=q->next q->next=p 你还是把他放 else 里面吧

可以不用if else 那个也是多余的

2024-11-22 08:08 UTC, Jonathan523 approved these changes

2024-11-22 15:27 UTC, blueshootingstar approved these changes

2024-11-24 13:32 UTC, lyyyyrrrrr approved these changes

2024-11-24 13:39 UTC, merged